"""This is a demo of the GPT-Vision-Prompt, DALL-E, Stability, and Finetune APIs.
"""


from gpt_vision_prompt import generate_prompt_with_vision
from dalle_generate_img import generate_img_with_dalle
from stability_generate_img import generate_image_with_stability
from finetune_generate_img import generate_finetuned_img
from midjourney_generate_img import midjourney_generate_img


# Path to your image
IMAGE_PATH = "img/img_030.jpg"
img_prompt = generate_prompt_with_vision(IMAGE_PATH,)
print(f"""Prompt generated by Vision:\n{img_prompt}""")

NEW_DALLE_IMG = generate_img_with_dalle(prompt=img_prompt)
NEW_STABILITY_IMG = generate_image_with_stability(prompt=img_prompt)
NEW_FINETUNED_IMG = generate_finetuned_img(prompt=img_prompt)
NEW_MIDJOURNEY_IMG = midjourney_generate_img(prompt=img_prompt)
